#!/usr/bin/env python3
"""
Refresh data/polymarket-calibration-baseline.csv from the PMA dataset
(Prediction Market Analysis — largest public Polymarket+Kalshi tape, 50GB of
parquet on /Volumes/Storage). The existing baseline (692M trades, 99 price
buckets) was generated by PMA's polymarket_win_rate_by_price analysis — this
script re-runs it against the current tape and refreshes the copybot's copy.

Also prints tape stats: total trades, win-rate by price bucket extremes.

Usage:
  python3 scripts/pma-refresh-baseline.py
"""
import json
import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PMA_DIR = "/tmp/pma"
PMA_VENV = os.path.join(PMA_DIR, ".venv", "bin", "python")
SRC_CSV = os.path.join(PMA_DIR, "output", "polymarket_win_rate_by_price.csv")
DST_CSV = os.path.join(ROOT, "data", "polymarket-calibration-baseline.csv")

ANALYSIS_SNIPPET = """
import sys, os
sys.path.insert(0, {{PMA_DIR}})
from src.analysis.polymarket.polymarket_win_rate_by_price import PolymarketWinRateByPriceAnalysis
a = PolymarketWinRateByPriceAnalysis()
out = a.run()
df = out.data if hasattr(out, 'data') else out
if df is not None:
    print('ROWS {}'.format(len(df)))
    print('TRADES {}'.format(int(df['total_trades'].sum())))
else:
    print('ROWS 0')
"""


def main():
    if not os.path.exists(PMA_VENV):
        print(f"PMA venv missing at {PMA_VENV} — clone PMA to /tmp/pma first")
        return 1
    if not os.path.isdir(os.path.join(PMA_DIR, "data")):
        print("PMA data symlink missing (expected /tmp/pma/data -> Storage)")
        return 1

    print("Running PMA win-rate-by-price analysis (40k parquet files, takes minutes)…")
    env = dict(os.environ, MPLBACKEND="Agg")
    snippet = ANALYSIS_SNIPPET.replace("{{PMA_DIR}}", repr(PMA_DIR))
    r = subprocess.run(
        [PMA_VENV, "-c", snippet],
        cwd=PMA_DIR, env=env, capture_output=True, text=True, timeout=3600,
    )
    if r.returncode != 0:
        print("Analysis failed:", r.stderr[-2000:])
        return 1
    for line in r.stdout.splitlines():
        if line.startswith(("ROWS", "TRADES")):
            print(line)

    if not os.path.exists(SRC_CSV):
        print(f"Expected output missing: {SRC_CSV}")
        return 1

    shutil.copy2(SRC_CSV, DST_CSV)
    n_lines = sum(1 for _ in open(DST_CSV))
    print(f"Refreshed {DST_CSV} ({n_lines} lines, {os.path.getsize(DST_CSV)//1024}KB)")
    print("Calibration page + analyze-calibration.py will pick it up on next load.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
